{
    "searchParameters": [
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 55,
            "amax": 55
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 56,
            "amax": 56
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 57,
            "amax": 57
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 58,
            "amax": 58
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 59,
            "amax": 59
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 60,
            "amax": 60
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 61,
            "amax": 61
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 62,
            "amax": 62
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 63,
            "amax": 63
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 64,
            "amax": 64
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 65,
            "amax": 65
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 66,
            "amax": 66
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 67,
            "amax": 67
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 68,
            "amax": 68
        },
                {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 69,
            "amax": 69
        },
        {
            "person": "Östra Göing",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 70,
            "amax": 70
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 55,
            "amax": 55
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 56,
            "amax": 56
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 57,
            "amax": 57
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 58,
            "amax": 58
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 59,
            "amax": 59
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 60,
            "amax": 60
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 61,
            "amax": 61
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 62,
            "amax": 62
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 63,
            "amax": 63
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 64,
            "amax": 64
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 65,
            "amax": 65
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 66,
            "amax": 66
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 67,
            "amax": 67
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 68,
            "amax": 68
        },
                {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 69,
            "amax": 69
        },
        {
            "person": "Örkelljunga",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 70,
            "amax": 70
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 55,
            "amax": 55
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 56,
            "amax": 56
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 57,
            "amax": 57
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 58,
            "amax": 58
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 59,
            "amax": 59
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 60,
            "amax": 60
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 61,
            "amax": 61
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 62,
            "amax": 62
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 63,
            "amax": 63
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 64,
            "amax": 64
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 65,
            "amax": 65
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 66,
            "amax": 66
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 67,
            "amax": 67
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 68,
            "amax": 68
        },
                {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 69,
            "amax": 69
        },
        {
            "person": "Åstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 70,
            "amax": 70
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 55,
            "amax": 55
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 56,
            "amax": 56
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 57,
            "amax": 57
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 58,
            "amax": 58
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 59,
            "amax": 59
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 60,
            "amax": 60
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 61,
            "amax": 61
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 62,
            "amax": 62
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 63,
            "amax": 63
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 64,
            "amax": 64
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 65,
            "amax": 65
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 66,
            "amax": 66
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 67,
            "amax": 67
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 68,
            "amax": 68
        },
                {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 69,
            "amax": 69
        },
        {
            "person": "Tomelilla",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 70,
            "amax": 70
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 55,
            "amax": 55
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 56,
            "amax": 56
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 57,
            "amax": 57
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 58,
            "amax": 58
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 59,
            "amax": 59
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 60,
            "amax": 60
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 61,
            "amax": 61
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 62,
            "amax": 62
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 63,
            "amax": 63
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 64,
            "amax": 64
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 65,
            "amax": 65
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 66,
            "amax": 66
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 67,
            "amax": 67
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 68,
            "amax": 68
        },
                {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 69,
            "amax": 69
        },
        {
            "person": "Svedala",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 70,
            "amax": 70
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 55,
            "amax": 55
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 56,
            "amax": 56
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 57,
            "amax": 57
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 58,
            "amax": 58
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 59,
            "amax": 59
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 60,
            "amax": 60
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 61,
            "amax": 61
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 62,
            "amax": 62
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 63,
            "amax": 63
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 64,
            "amax": 64
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 65,
            "amax": 65
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 66,
            "amax": 66
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 67,
            "amax": 67
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 68,
            "amax": 68
        },
                {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 69,
            "amax": 69
        },
        {
            "person": "Sjöbo",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 70,
            "amax": 70
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 55,
            "amax": 55
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 56,
            "amax": 56
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 57,
            "amax": 57
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 58,
            "amax": 58
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 59,
            "amax": 59
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 60,
            "amax": 60
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 61,
            "amax": 61
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 62,
            "amax": 62
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 63,
            "amax": 63
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 64,
            "amax": 64
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 65,
            "amax": 65
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 66,
            "amax": 66
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 67,
            "amax": 67
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 68,
            "amax": 68
        },
                {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 69,
            "amax": 69
        },
        {
            "person": "Skurup",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 70,
            "amax": 70
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 55,
            "amax": 55
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 56,
            "amax": 56
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 57,
            "amax": 57
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 58,
            "amax": 58
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 59,
            "amax": 59
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 60,
            "amax": 60
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 61,
            "amax": 61
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 62,
            "amax": 62
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 63,
            "amax": 63
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 64,
            "amax": 64
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 65,
            "amax": 65
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 66,
            "amax": 66
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 67,
            "amax": 67
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 68,
            "amax": 68
        },
                {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 69,
            "amax": 69
        },
        {
            "person": "Perstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 70,
            "amax": 70
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 55,
            "amax": 55
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 56,
            "amax": 56
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 57,
            "amax": 57
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 58,
            "amax": 58
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 59,
            "amax": 59
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 60,
            "amax": 60
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 61,
            "amax": 61
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 62,
            "amax": 62
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 63,
            "amax": 63
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 64,
            "amax": 64
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 65,
            "amax": 65
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 66,
            "amax": 66
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 67,
            "amax": 67
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 68,
            "amax": 68
        },
                {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 69,
            "amax": 69
        },
        {
            "person": "Osby",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 70,
            "amax": 70
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 55,
            "amax": 55
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 56,
            "amax": 56
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 57,
            "amax": 57
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 58,
            "amax": 58
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 59,
            "amax": 59
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 60,
            "amax": 60
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 61,
            "amax": 61
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 62,
            "amax": 62
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 63,
            "amax": 63
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 64,
            "amax": 64
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 65,
            "amax": 65
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 66,
            "amax": 66
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 67,
            "amax": 67
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 68,
            "amax": 68
        },
                {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 69,
            "amax": 69
        },
        {
            "person": "Staffanstorp",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 70,
            "amax": 70
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 55,
            "amax": 55
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 56,
            "amax": 56
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 57,
            "amax": 57
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 58,
            "amax": 58
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 59,
            "amax": 59
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 60,
            "amax": 60
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 61,
            "amax": 61
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 62,
            "amax": 62
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 63,
            "amax": 63
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 64,
            "amax": 64
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 65,
            "amax": 65
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 66,
            "amax": 66
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 67,
            "amax": 67
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 68,
            "amax": 68
        },
                {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 69,
            "amax": 69
        },
        {
            "person": "Landskrona",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 70,
            "amax": 70
        }

    ],
    "pages": "16",
    "fileName": "Skåne del 2 55-70"
}