{
    "searchParameters": [
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 42,
            "amax": 42
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 43,
            "amax": 43
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 44,
            "amax": 44
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 45,
            "amax": 45
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 46,
            "amax": 46
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 47,
            "amax": 47
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 48,
            "amax": 48
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 49,
            "amax": 49
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 50,
            "amax": 50
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 51,
            "amax": 51
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 52,
            "amax": 52
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 53,
            "amax": 53
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 54,
            "amax": 54
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 55,
            "amax": 55
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 56,
            "amax": 56
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 57,
            "amax": 57
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 58,
            "amax": 58
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 59,
            "amax": 59
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 60,
            "amax": 60
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 61,
            "amax": 61
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 62,
            "amax": 62
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 63,
            "amax": 63
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 64,
            "amax": 64
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 65,
            "amax": 65
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 66,
            "amax": 66
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 67,
            "amax": 67
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 68,
            "amax": 68
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 69,
            "amax": 69
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 70,
            "amax": 70
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 71,
            "amax": 71
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 72,
            "amax": 72
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 73,
            "amax": 73
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 74,
            "amax": 74
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 75,
            "amax": 75
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 76,
            "amax": 76
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 77,
            "amax": 77
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 78,
            "amax": 78
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 79,
            "amax": 79
        },
        {
            "person": "Arjeplog",
            "m": "0",
            "k": "0",
            "r": "0",
            "er": "0",
            "b": "1",
            "eb": "0",
            "amin": 80,
            "amax": 80
        },
    ],
    "pages": "16",
    "fileName": "Arjeplog 44-80"
}